
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "public";

ALTER SCHEMA "public" OWNER TO "pg_database_owner";

CREATE TYPE "public"."media_type" AS ENUM (
    'Movie',
    'Show'
);

ALTER TYPE "public"."media_type" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."actors" (
    "id" bigint NOT NULL,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "country_id" bigint NOT NULL,
    "image" text
);

ALTER TABLE "public"."actors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."countries" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."countries" OWNER TO "postgres";

ALTER TABLE "public"."countries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."countries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."directors" (
    "id" bigint NOT NULL,
    "first_name" text NOT NULL,
    "last_name" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "country_id" bigint NOT NULL,
    "image" text
);

ALTER TABLE "public"."directors" OWNER TO "postgres";

ALTER TABLE "public"."directors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."directors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."episodes" (
    "id" bigint NOT NULL,
    "number" bigint NOT NULL,
    "image" text NOT NULL,
    "video_url" text NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "season_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "duration" text NOT NULL
);

ALTER TABLE "public"."episodes" OWNER TO "postgres";

ALTER TABLE "public"."episodes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."episodes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."genres" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "title" text,
    "image" text,
    "top" boolean
);

ALTER TABLE "public"."genres" OWNER TO "postgres";

ALTER TABLE "public"."genres" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."genres_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."languages" (
    "id" bigint NOT NULL,
    "title" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."languages" OWNER TO "postgres";

ALTER TABLE "public"."languages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."languages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."media" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "image" text NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "duration" text,
    "trending" boolean,
    "views" numeric,
    "must_watch" boolean,
    "top" boolean,
    "votes" numeric DEFAULT '0'::numeric NOT NULL,
    "banner" text NOT NULL,
    "media_type" public.media_type,
    "season" numeric
);

ALTER TABLE "public"."media" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."media_actors" (
    "movie_id" integer NOT NULL,
    "member_id" integer NOT NULL
);

ALTER TABLE "public"."media_actors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."media_directors" (
    "media_id" integer NOT NULL,
    "director_id" integer NOT NULL
);

ALTER TABLE "public"."media_directors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."media_genres" (
    "movie_id" integer NOT NULL,
    "genre_id" integer NOT NULL
);

ALTER TABLE "public"."media_genres" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."media_languages" (
    "movie_id" integer NOT NULL,
    "language_id" integer NOT NULL
);

ALTER TABLE "public"."media_languages" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."media_musicians" (
    "media_id" integer NOT NULL,
    "musician_id" integer NOT NULL
);

ALTER TABLE "public"."media_musicians" OWNER TO "postgres";

ALTER TABLE "public"."actors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."media" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."movies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."musicians" (
    "id" bigint NOT NULL,
    "first_name" text NOT NULL,
    "last_name" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "country_id" bigint NOT NULL,
    "image" text
);

ALTER TABLE "public"."musicians" OWNER TO "postgres";

ALTER TABLE "public"."musicians" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."musicians_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."reviews" (
    "id" bigint NOT NULL,
    "description" text NOT NULL,
    "rating" numeric,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "media_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);

ALTER TABLE "public"."reviews" OWNER TO "postgres";

ALTER TABLE "public"."reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."roles" OWNER TO "postgres";

ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "id" bigint NOT NULL,
    "number" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "media_id" bigint NOT NULL
);

ALTER TABLE "public"."seasons" OWNER TO "postgres";

ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."shows" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "image" text NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "duration" text,
    "trending" boolean,
    "must_watch" boolean,
    "season" numeric,
    "votes" numeric DEFAULT '0'::numeric NOT NULL
);

ALTER TABLE "public"."shows" OWNER TO "postgres";

ALTER TABLE "public"."shows" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."shows_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "first_name" text NOT NULL,
    "last_name" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "country_id" bigint
);

ALTER TABLE "public"."users" OWNER TO "postgres";

ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."directors"
    ADD CONSTRAINT "directors_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."episodes"
    ADD CONSTRAINT "episodes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."genres"
    ADD CONSTRAINT "genres_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."languages"
    ADD CONSTRAINT "languages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."media_directors"
    ADD CONSTRAINT "media_directors_pkey" PRIMARY KEY ("media_id", "director_id");

ALTER TABLE ONLY "public"."media_musicians"
    ADD CONSTRAINT "media_musicians_pkey" PRIMARY KEY ("media_id", "musician_id");

ALTER TABLE ONLY "public"."actors"
    ADD CONSTRAINT "members_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."media_genres"
    ADD CONSTRAINT "movie_genres_pkey" PRIMARY KEY ("movie_id", "genre_id");

ALTER TABLE ONLY "public"."media_languages"
    ADD CONSTRAINT "movie_languages_pkey" PRIMARY KEY ("movie_id", "language_id");

ALTER TABLE ONLY "public"."media_actors"
    ADD CONSTRAINT "movie_members_pkey" PRIMARY KEY ("movie_id", "member_id");

ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "movies_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."musicians"
    ADD CONSTRAINT "musicians_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."shows"
    ADD CONSTRAINT "shows_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."actors"
    ADD CONSTRAINT "actors_country_id_fkey" FOREIGN KEY (country_id) REFERENCES public.countries(id);

ALTER TABLE ONLY "public"."directors"
    ADD CONSTRAINT "directors_country_id_fkey" FOREIGN KEY (country_id) REFERENCES public.countries(id);

ALTER TABLE ONLY "public"."episodes"
    ADD CONSTRAINT "episodes_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."media_actors"
    ADD CONSTRAINT "media_actors_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.actors(id);

ALTER TABLE ONLY "public"."media_actors"
    ADD CONSTRAINT "media_actors_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES public.media(id);

ALTER TABLE ONLY "public"."media_directors"
    ADD CONSTRAINT "media_directors_director_id_fkey" FOREIGN KEY (director_id) REFERENCES public.directors(id);

ALTER TABLE ONLY "public"."media_directors"
    ADD CONSTRAINT "media_directors_media_id_fkey" FOREIGN KEY (media_id) REFERENCES public.media(id);

ALTER TABLE ONLY "public"."media_genres"
    ADD CONSTRAINT "media_genres_genre_id_fkey" FOREIGN KEY (genre_id) REFERENCES public.genres(id);

ALTER TABLE ONLY "public"."media_genres"
    ADD CONSTRAINT "media_genres_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES public.media(id);

ALTER TABLE ONLY "public"."media_languages"
    ADD CONSTRAINT "media_languages_language_id_fkey" FOREIGN KEY (language_id) REFERENCES public.languages(id);

ALTER TABLE ONLY "public"."media_languages"
    ADD CONSTRAINT "media_languages_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES public.media(id);

ALTER TABLE ONLY "public"."media_musicians"
    ADD CONSTRAINT "media_musicians_media_id_fkey" FOREIGN KEY (media_id) REFERENCES public.media(id);

ALTER TABLE ONLY "public"."media_musicians"
    ADD CONSTRAINT "media_musicians_musician_id_fkey" FOREIGN KEY (musician_id) REFERENCES public.musicians(id);

ALTER TABLE ONLY "public"."musicians"
    ADD CONSTRAINT "musicians_country_id_fkey" FOREIGN KEY (country_id) REFERENCES public.countries(id);

ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_media_id_fkey" FOREIGN KEY (media_id) REFERENCES public.media(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_media_id_fkey" FOREIGN KEY (media_id) REFERENCES public.media(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_country_id_fkey" FOREIGN KEY (country_id) REFERENCES public.countries(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Enable read access for all users" ON "public"."actors" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."countries" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."directors" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."episodes" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."genres" USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."languages" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media_actors" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media_directors" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media_genres" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media_languages" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."media_musicians" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."musicians" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."reviews" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."roles" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."seasons" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."shows" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."users" FOR SELECT USING (true);

ALTER TABLE "public"."actors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."countries" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."directors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."episodes" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."genres" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."languages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_actors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_directors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_genres" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_languages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."media_musicians" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."musicians" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."shows" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."actors" TO "anon";
GRANT ALL ON TABLE "public"."actors" TO "authenticated";
GRANT ALL ON TABLE "public"."actors" TO "service_role";

GRANT ALL ON TABLE "public"."countries" TO "anon";
GRANT ALL ON TABLE "public"."countries" TO "authenticated";
GRANT ALL ON TABLE "public"."countries" TO "service_role";

GRANT ALL ON SEQUENCE "public"."countries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."countries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."countries_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."directors" TO "anon";
GRANT ALL ON TABLE "public"."directors" TO "authenticated";
GRANT ALL ON TABLE "public"."directors" TO "service_role";

GRANT ALL ON SEQUENCE "public"."directors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."directors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."directors_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."episodes" TO "anon";
GRANT ALL ON TABLE "public"."episodes" TO "authenticated";
GRANT ALL ON TABLE "public"."episodes" TO "service_role";

GRANT ALL ON SEQUENCE "public"."episodes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."episodes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."episodes_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."genres" TO "anon";
GRANT ALL ON TABLE "public"."genres" TO "authenticated";
GRANT ALL ON TABLE "public"."genres" TO "service_role";

GRANT ALL ON SEQUENCE "public"."genres_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."genres_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."genres_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."languages" TO "anon";
GRANT ALL ON TABLE "public"."languages" TO "authenticated";
GRANT ALL ON TABLE "public"."languages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."media" TO "anon";
GRANT ALL ON TABLE "public"."media" TO "authenticated";
GRANT ALL ON TABLE "public"."media" TO "service_role";

GRANT ALL ON TABLE "public"."media_actors" TO "anon";
GRANT ALL ON TABLE "public"."media_actors" TO "authenticated";
GRANT ALL ON TABLE "public"."media_actors" TO "service_role";

GRANT ALL ON TABLE "public"."media_directors" TO "anon";
GRANT ALL ON TABLE "public"."media_directors" TO "authenticated";
GRANT ALL ON TABLE "public"."media_directors" TO "service_role";

GRANT ALL ON TABLE "public"."media_genres" TO "anon";
GRANT ALL ON TABLE "public"."media_genres" TO "authenticated";
GRANT ALL ON TABLE "public"."media_genres" TO "service_role";

GRANT ALL ON TABLE "public"."media_languages" TO "anon";
GRANT ALL ON TABLE "public"."media_languages" TO "authenticated";
GRANT ALL ON TABLE "public"."media_languages" TO "service_role";

GRANT ALL ON TABLE "public"."media_musicians" TO "anon";
GRANT ALL ON TABLE "public"."media_musicians" TO "authenticated";
GRANT ALL ON TABLE "public"."media_musicians" TO "service_role";

GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."members_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."musicians" TO "anon";
GRANT ALL ON TABLE "public"."musicians" TO "authenticated";
GRANT ALL ON TABLE "public"."musicians" TO "service_role";

GRANT ALL ON SEQUENCE "public"."musicians_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."musicians_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."musicians_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."reviews" TO "anon";
GRANT ALL ON TABLE "public"."reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."reviews" TO "service_role";

GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";

GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."seasons" TO "anon";
GRANT ALL ON TABLE "public"."seasons" TO "authenticated";
GRANT ALL ON TABLE "public"."seasons" TO "service_role";

GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."seasons_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."shows" TO "anon";
GRANT ALL ON TABLE "public"."shows" TO "authenticated";
GRANT ALL ON TABLE "public"."shows" TO "service_role";

GRANT ALL ON SEQUENCE "public"."shows_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."shows_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."shows_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
